version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: library-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-backend
    restart: unless-stopped
    environment:
      APP_PORT: 8080
      APP_NAME: library-management-api
      DB_URL: postgres://postgres:postgres@db:5432/library?sslmode=disable
      DB_MAX_IDLE_CONN: 10
      DB_MAX_OPEN_CONN: 20
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local